apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - /busybox/cat
      tty: true
      env:
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_SDK_LOAD_CONFIG
          value: "true"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

    - name: helm
      image: alpine/helm:3.14.4
      command:
        - cat
      tty: true

  volumes:
    - name: docker-config
      emptyDir: {}
