apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-agent
spec:
  serviceAccountName: jenkins
  restartPolicy: Never

  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: maven-cache
          mountPath: /root/.m2
        - name: npm-cache
          mountPath: /root/.npm

    - name: tools
      image: alpine/helm:3.14.4
      command:
        - sh
        - -c
        - |
          apk add --no-cache curl bash aws-cli kubectl && sleep infinity
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

    - name: jnlp
      image: jenkins/inbound-agent:latest
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent

  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: docker-config
      emptyDir: {}
    - name: maven-cache
      emptyDir: {}
    - name: npm-cache
      emptyDir: {}
